# Generated by Django 5.1.3 on 2024-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_rfid', models.CharField(max_length=255)),
                ('key_rfid', models.CharField(max_length=255)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_rfid', models.CharField(max_length=255, unique=True)),
                ('key_rfid', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='KeyInteractionLog',
        ),
    ]
