# Generated by Django 5.1.3 on 2024-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_history_temporary_delete_keyinteractionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='status',
        ),
        migrations.AlterField(
            model_name='key',
            name='rfid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
