# Generated by Django 5.1.3 on 2024-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_key_status_alter_key_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='status',
            field=models.CharField(default='Returned', max_length=10),
        ),
        migrations.AlterField(
            model_name='key',
            name='rfid',
            field=models.CharField(default='Returned', max_length=100),
        ),
    ]
