# Generated by Django 5.1.3 on 2024-11-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_key_status_alter_key_rfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='status',
        ),
        migrations.AlterField(
            model_name='key',
            name='rfid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
